repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      #- id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-byte-order-marker  # Forbid UTF-8 byte-order markers

  - repo: https://github.com/pycqa/autoflake
    rev: v2.3.1
    hooks:
    - id: autoflake
      args: [--remove-all-unused-imports, --in-place]

  # -----------------------------
  # autopep8
  # -----------------------------
  # - repo: https://github.com/pre-commit/mirrors-autopep8
  #   rev: v2.0.4
  #   hooks:
  #     - id: autopep8
  #       args:
  #         - --in-place
  #         - --aggressive
  #       files: \.py$

  # -----------------------------
  # isort (import)
  # -----------------------------
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args:
          - --profile=black
        files: \.py$

  # -----------------------------
  # black (formatter)
  # ------------------------------
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.2
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3
        args: ["--line-length=100"]

  # -----------------------------
  # flake8 (lint)
  # -----------------------------

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ["--ignore=E501,W503,F841,F821"]

  # -----------------------------
  # pydocstyle (PEP257)
  # -----------------------------
  # - repo: https://github.com/pycqa/pydocstyle
  #   rev: 6.3.0
  #   hooks:
  #     - id: pydocstyle
