startup:
  renderer: "RaytracedLighting"
  headless: False
  anti_aliasing: 0
  verbose: True
  step_freq: 60

world:
  stage_units_in_meters: 1.0
  package: "tm5-900_rg6_moveit_config"
  usd_path: "config/tm5-900/tm5-900_real.usd"

extensions:
  - isaacsim.storage.native
