---
std_msgs/Header header

sensor_msgs/JointState arm_action
sensor_msgs/JointState arm_state

sensor_msgs/JointState gripper_action
sensor_msgs/JointState gripper_state

sensor_msgs/Image camera


bool success
string message
---
std_msgs/Header header

sensor_msgs/JointState arm_action
sensor_msgs/JointState arm_state

sensor_msgs/JointState gripper_action
sensor_msgs/JointState gripper_state

sensor_msgs/Image camera

bool success
string message